### ISSUE TITLE
available sm ext version

### ISSUE THREAD

**Issue by ProjectSky** [FortyTwoFortyTwo/VScript#1]
have you try this extension https://github.com/jonatan1024/vscriptfun? It should work on tf2

[vscriptfun.zip](https://github.com/FortyTwoFortyTwo/VScript/files/11399320/vscriptfun.zip)

**Comment by FortyTwoFortyTwo** [comment]
I was not aware of this extension, and it certainly does looks like one way you can use VScript in SM.

Not to put shade on dev, but i'd argue that mine gives a lot more options on what you can do with it, like looping though a list of it, get more info on each of it, auto-create SDKCall and DHooks of its function, literate though hscript table keys and values, and a lot more while i want to add even more support of it.
