### ISSUE TITLE
Error detected in plugin startup (see error logs)

### ISSUE THREAD

**Issue by perromeao13** [FortyTwoFortyTwo/VScript#11]
I am trying to run the plugin, but I am getting this error:

[SM] Unrecognized library "vscript" (gameconf "/home/container/tf/addons/sourcemod/gamedata/__vscript__.txt")
[SM] Unrecognized library "vscript" (gameconf "/home/container/tf/addons/sourcemod/gamedata/__vscript__.txt")
[SM] Exception reported: Invalid address 0x5c is pointing to reserved memory.
[SM] Blaming: vscript.smx
[SM] Call stack trace:
[SM]   [0] LoadFromAddress
[SM]   [1] Line 129, vscript\vtable.sp::VTable_GetAddressFromName
[SM]   [2] Line 94, vscript\util.sp::CreateSDKCall
[SM]   [3] Line 30, vscript\entity.sp::Entity_LoadGamedata
[SM]   [4] Line 157, C:\Users\yop\Documents\scripting\vscript.sp::OnPluginStart
[SM]   [6] ServerCommandEx
[SM]   [7] Line 402, /home/builds/sourcemod/debian9-1.11/build/plugins/basecommands.sp::Command_Rcon

**Comment by FortyTwoFortyTwo** [comment]
You need to use sourcemod version `1.12.0.6924` or higher to have library support "vscript".
