### ISSUE TITLE
[vscript.smx] Invalid class in VTable 'IScriptVM'

### ISSUE THREAD

**Issue by SefoNotasi** [FortyTwoFortyTwo/VScript#15]
I upgraded VScript from version 1.8.6.81 to 1.9.1.85 from [this build](https://github.com/FortyTwoFortyTwo/VScript/actions/runs/11622699901)
After that the VScript plugin stopped running and throws the following error:

**L 11/09/2024 - 03:17:51: SourceMod error session started
L 11/09/2024 - 03:17:51: Info (map "c1m2_streets") (file "/home/steam/ds5/left4dead2/addons/sourcemod/logs/errors_20241109.log")
L 11/09/2024 - 03:17:51: [vscript.smx] Invalid class in VTable 'IScriptVM'
L 11/09/2024 - 03:17:51: [SM] Exception reported: Invalid address 0x5c is pointing to reserved memory.
L 11/09/2024 - 03:17:51: [SM] Blaming: vscript.smx
L 11/09/2024 - 03:17:51: [SM] Call stack trace:
L 11/09/2024 - 03:17:51: [SM]   [0] LoadFromAddress
L 11/09/2024 - 03:17:51: [SM]   [1] Line 129, vscript/vtable.sp::VTable_GetAddressFromName
L 11/09/2024 - 03:17:51: [SM]   [2] Line 108, vscript/util.sp::CreateSDKCall
L 11/09/2024 - 03:17:51: [SM]   [3] Line 30, vscript/entity.sp::Entity_LoadGamedata
L 11/09/2024 - 03:17:51: [SM]   [4] Line 166, vscript.sp::OnPluginStart
L 11/09/2024 - 03:17:51: [SM] Unable to load plugin "vscript.smx": Error detected in plugin startup (see error logs)
L 11/09/2024 - 03:18:05: Error log file session closed.
L 11/09/2024 - 03:18:05: SourceMod error session started
L 11/09/2024 - 03:18:05: Info (map "c14m1_junkyard") (file "/home/steam/ds5/left4dead2/addons/sourcemod/logs/errors_20241109.log")
L 11/09/2024 - 03:18:05: [SM] Unable to load plugin "l4d2_sb_ai_improver.smx": Could not find required plugin "vscript"
L 11/09/2024 - 12:54:02: Error log file session closed.**

I tried installing a [penultimate build with the same version](https://github.com/FortyTwoFortyTwo/VScript/actions/runs/11430023527) and it works without errors.

Server on linux (Ubuntu server minimized).
mmsource-1.11.0-git1155-linux
sourcemod-1.12.0-git7167-linux
SMExt-SourceScramble 0.8.0-pre2
Actions 3.8.8

**Comment by FortyTwoFortyTwo** [comment]
> I tried installing a [penultimate build with the same version](https://github.com/FortyTwoFortyTwo/VScript/actions/runs/11430023527) and it works without errors.

I can only image of a SourcePawn update if this were to be the case, which current latest version is not very stable.
I may have to force use specific SP version to build if there to be the case.

**Comment by FortyTwoFortyTwo** [comment]
[Made an issue](https://github.com/alliedmodders/sourcepawn/issues/995) on what's directly caused from this bug occurring from `g_VTableGameData` variable.

**Comment by FortyTwoFortyTwo** [comment]
Made a commit on moving packages to releases, which should also have the fixed SP version
