### ISSUE TITLE
`VENCODE_FLAG_COPYBACK` causes HSCRIPT.SetValue to return bad value

### ISSUE THREAD

**Issue by KitRifty** [FortyTwoFortyTwo/VScript#2]
On TF2 Windows, the `HSCRIPT.SetValue` native returns false even if the actual operation was successful.

For example, running the line `HSCRIPT_RootTable.SetValue("m_test_value", FIELD_INTEGER, 123);` will throw the error "Invalid HSCRIPT object '0'".

However, the value was actually assigned successfully when viewing it using the command `script printl(m_test_value)` in the server console:

![image](https://github.com/FortyTwoFortyTwo/VScript/assets/4492504/48bfbfee-6123-47d7-9ae9-b3302809917e)

After stripping the `VENCODE_FLAG_COPYBACK` encode flag from the `CreateSDKCall` function, the native no longer throws an error.

**Comment by FortyTwoFortyTwo** [comment]
I lazy copied the code from `Function_CreateSDKCall`, but yeah seems like that flag is not needed from any functions using `CreateSDKCall`. Thanks for the report!
