### ISSUE TITLE
[L4D2] server crash

### ISSUE THREAD

**Issue by ProjectSky** [FortyTwoFortyTwo/VScript#6]
OS: Linux

* console
```
sm plugins load vscript
VSCRIPT: Running mapspawn.nut
CSpeechScriptBridge was double-initialized: tearing down and rebuilding
        HSCRIPT loaded successfully
[SM] Loaded plugin vscript.smx successfully.

changelevel c1m1_hotel
Segmentation fault (core dumped)
**** server crash ****
```

**Comment by FortyTwoFortyTwo** [comment]
I don't have a L4D2 linux server to test it out, so it will be tough for me to test it out myself. Do you have crash log from Accelerator extension for a more detailed info?

**Comment by ProjectSky** [comment]
unknown issue with sm1.12, I can't upload crash logs using the accelerator
sm1.11 can upload crash logs, but this plugin can only run on sm1.12. so i can't provide crash logs
```
Response module list doesn't match sent list (33 < 49)
```

recreate this issues is easy
1: Start the server
2: Load/reload this plugin
3: Change the map
4: Server crashes

**Comment by FortyTwoFortyTwo** [comment]
When a vscript plugin is loaded, are you able to use vscript functions as normal, and/or using plugin's natives before changelevel? There is `vscript_test.sp` plugin you can test it out to see if all tests passed.

**Comment by ProjectSky** [comment]
test failed

```
L 06/29/2023 - 01:10:33: [SM] Exception reported: Could not find class name 'CBaseEntity'
L 06/29/2023 - 01:10:33: [SM] Blaming: vscript.smx
L 06/29/2023 - 01:10:33: [SM] Call stack trace:
L 06/29/2023 - 01:10:33: [SM]   [0] ThrowNativeError
L 06/29/2023 - 01:10:33: [SM]   [1] Line 734, vscript.sp::Native_GetClassFunction
L 06/29/2023 - 01:10:33: [SM]   [3] VScript_GetClassFunction
L 06/29/2023 - 01:10:33: [SM]   [4] Line 464, F:\Desktop\scripting\include\vscript.inc::VScript_CreateClassFunction
L 06/29/2023 - 01:10:33: [SM]   [5] Line 43, f:\Desktop\scripting\vscript_test.sp::OnMapStart
```

crash seems to only happen on the linux, I test the win server no crash

**Comment by FortyTwoFortyTwo** [comment]
This took me some time to figure it out, and i'm not sure if this is even the cause of the crash. I've pushed a branch that prevents `CSpeechScriptBridge` get double created, see if this helps it or makes any difference.
https://github.com/FortyTwoFortyTwo/VScript/actions/runs/5405804057

**Comment by ProjectSky** [comment]
no luck, crash again
Here is the dump file generated by the accelerator, hope it helps

[CrashDmp.zip](https://github.com/FortyTwoFortyTwo/VScript/files/11900906/CrashDmp.zip)

**Comment by FortyTwoFortyTwo** [comment]
This crash dump does helps it, which it's related to deleting `CSpeechScriptBridge` class.

Updated l4d2-crash branch to see if blocking deletion helps it, give it a try.
https://github.com/FortyTwoFortyTwo/VScript/actions/runs/5413177454

**Comment by ProjectSky** [comment]
didn't help, new version still crash

**Comment by FortyTwoFortyTwo** [comment]
could you give a new crash dumper to see if any difference on crash log were reported

**Comment by ProjectSky** [comment]
[CrashDump-20230630.zip](https://github.com/FortyTwoFortyTwo/VScript/files/11911829/CrashDump-20230630.zip)

**Comment by FortyTwoFortyTwo** [comment]
Crash log gives same result, so i'm missing something out. Trying out a different method instead, make sure that you've also been updating gamedata from builds.
https://github.com/FortyTwoFortyTwo/VScript/actions/runs/5423524556

**Comment by ProjectSky** [comment]
same result
[CrashDump-20230701.zip](https://github.com/FortyTwoFortyTwo/VScript/files/11918517/CrashDump-20230701.zip)

**Comment by FortyTwoFortyTwo** [comment]
I don't really have any other ideas on how to fix it properly without having a linux server myself for it.
Did a temporary workaround fix, which should be good enough to load a plugin on server start without crash.
https://github.com/FortyTwoFortyTwo/VScript/actions/runs/5433330247

**Comment by ProjectSky** [comment]
server crash trying to load plugin :(
I give up, thanks for the multiple fixes

**Comment by FortyTwoFortyTwo** [comment]
For now i've updated plugin to prevent any attempts to reset g_pScriptVM, so not all features will work properly until a mapchange occurs.

**Comment by ProjectSky** [comment]
> For now i've updated plugin to prevent any attempts to reset g_pScriptVM, so not all features will work properly until a mapchange occurs.

I've tried the new version and it crash the server as soon as the plugin is loaded

**Comment by FortyTwoFortyTwo** [comment]
Make sure that you have truly updated the plugin AND gamedata, because otherwise I see no other reason it can break..

**Comment by ProjectSky** [comment]
update to the latest version server no crash anymore, but when I try to load vscript_test it throws error: ```Could not find class name CBaseEntity```

```
L 07/20/2023 - 19:27:07: [SM] Exception reported: Could not find class name 'CBaseEntity'
L 07/20/2023 - 19:27:07: [SM] Blaming: vscript.smx
L 07/20/2023 - 19:27:07: [SM] Call stack trace:
L 07/20/2023 - 19:27:07: [SM]   [0] ThrowNativeError
L 07/20/2023 - 19:27:07: [SM]   [1] Line 763, vscript.sp::Native_GetClassFunction
L 07/20/2023 - 19:27:07: [SM]   [3] VScript_GetClassFunction
L 07/20/2023 - 19:27:07: [SM]   [4] Line 475, f:\Desktop\scripting\include\vscript.inc::VScript_CreateClassFunction
L 07/20/2023 - 19:27:07: [SM]   [5] Line 43, f:\Desktop\scripting\vscript_test.sp::OnMapStart
```
only happens when the vscript_test load or changelevel

**Comment by FortyTwoFortyTwo** [comment]
Surprised to hear that it no longer crashes, assuming that `AllowResetScriptVM` in gamedata is at 1 for L4D2 linux.
I've updated it again which should fix the missing class error.

**Comment by ProjectSky** [comment]
I found that most of L4D2 vscript class are not registered when the game is loaded, maybe L4D2 has a different loading method, is very strange

``` c
public void OnMapStart()
{
	ArrayList classes = VScript_GetAllClasses();
	char buffer[32];

	for (int i = 0; i <= classes.Length; i++)
	{
		VScriptClass cls = classes.Get(i);
		cls.GetScriptName(buffer, sizeof(buffer));
		PrintToServer("cls: %s", buffer);
	}

	delete classes;
}
```

* empty server (no players joined)
```
cls: CBaseCombatCharacter
cls: CBaseAnimating
```

* player join server
```
cls: CDirector
cls: CNavMesh
cls: CEntities
cls: Convars
cls: CScriptEntityOutputs
cls: CNetPropManager
cls: CScriptResponseCriteria
cls: Decider
cls: CBaseEntity
cls: CBaseAnimating
cls: CBaseTrigger
cls: CBaseFlex
cls: CTerrorWeapon
```

* after a few seconds
```
cls: CDirector
cls: CNavMesh
cls: CEntities
cls: Convars
cls: CScriptEntityOutputs
cls: CNetPropManager
cls: CScriptResponseCriteria
cls: Decider
cls: CBaseEntity
cls: CBaseAnimating
cls: CBaseTrigger
cls: CBaseFlex
cls: CTerrorWeapon
cls: CTerrorPlayer
cls: CBaseCombatCharacter
```

**Comment by FortyTwoFortyTwo** [comment]
Indeed that L4D2 load classes differently to CSGO and TF2, as it only registers it when actually needed. So plugin will have a harder time trying to get all classes, needing to rely on existing entities in map to collect it. I'm not sure if there is a way to automatically collect all of it, would love to hear it.

But since this issue is about the crash, would be best to open a new issue assuming that the crash is fixed.

**Comment by ProjectSky** [comment]
> But since this issue is about the crash, would be best to open a new issue assuming that the crash is fixed.

I test it many times, the crash issues should have been fixed. i will close this issues

thx for your work
